version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test

  build_python_package:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Copy schema dir content to python dir
          command: cp ./schema/*.json ./python/artfullylondon/ingestschema/
      - run:
          name: Copy license file
          command: cp ./LICENSE ./python/LICENSE
      - run:
          name: Install python dependencies
          command: pip install --user setuptools twine wheel
      - run:
          name: Build package
          command: cd ./python && python3 setup.py sdist bdist_wheel
      - run:
          name: Upload package to pipy
          command: cd ./python && python3 -m twine upload --skip-existing dist/*

workflows:
  version: 2
  build:
    jobs:
      - test
      - build_python_package:
          filters:
            branches:
              only: master
