version: 2.1

jobs:
  build_python_package:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/project/python
    steps:
      - checkout
      - run:
          name: temp2
          command: ls
      - run:
          name: Copy schema dir content to python dir
          command: cp ../schema/*.json ./artfullylondon/ingestschema/
      - run:
          name: Copy license file
          command: cp ../LICENSE ./LICENSE
      - run:
          name: temp
          command: ls
      - run:
          name: Install python dependencies
          command: pip install --user setuptools twine wheel
      - run:
          name: Build package
          command: python3 setup.py sdist bdist_wheel
      - run:
          name: Upload package to pipy
          command: python3 -m twine upload dist/*

workflows:
  version: 2
  build:
    jobs:
      - build_python_package:
          filters:
            branches:
              only: master
